### ISSUE TITLE
Wrong encoding

### ISSUE THREAD

**Issue by alehano** [warthog618/sms#7]
Hello. Thank you for a great project. 
I faced with a problem. I'm trying to encode tpdu sms to send it from sim800l GSM module and got an error. While SMS encoded with online tool https://www.smsdeliverer.com/online-sms-pdu-encoder.aspx module sending fine.
Result tpdu:
From online tool (length 26) - 0011000B919730171111F10008FF0C041F04400438043204350442
From this package (length 25) -  01010b919730171111f100080c041f04400438043204350442
Vise versa I can't decode tpdu with online tool https://www.smspdu.be/ while the first (decoded online) tpdu works fine.

Also tpdu mentioned in a Readme file of this project - 010105912143f500000bc8329bfd06dddf723619 can't be decoded with online tool https://www.smspdu.be/

My code: 
```golang
	var number, msg = "+79037111111", "Привет"
	options := []sms.EncoderOption{sms.To(number)}
	pdus, err := sms.Encode([]byte(msg), options...)
	if err != nil {
		log.Println(err)
		return
	}
	for i, p := range pdus {
		b, _ := p.MarshalBinary()
		fmt.Printf("Submit TPDU %d (len %d):\n%s\n", i+1, len(b), hex.EncodeToString(b))
	}
```

**Comment by warthog618** [comment]
That is a Submit TPDU, so prefix it with "00" to decode it at that site.
Or try https://www.diafaan.com/sms-tutorials/gsm-modem-tutorial/online-sms-submit-pdu-decoder/.
Both work for me with all examples you mention.

**Comment by warthog618** [comment]
And you might want to take a look at my modem library.  That includes a gsm module that does what you probably need without having to know the details of the encoding.

**Comment by alehano** [comment]
Great! Thanks. The modem library very handy
